name: Update README

on:
  push:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update

    steps:
      - uses: actions/checkout@v2
      - run: node index.js
      - uses: stefanzweifel/git-auto-commit-action@v4
