name: Update stat

on:
  workflow_dispatch: 
  push:
  schedule:
    # Runs at 12am UTC
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run:  npm install replace 
      
      - name: Hi
        run: node editfile.js
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add image
